---
- hosts: solr
  become: true  

  vars_files:
    - vars.yaml
  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart solr
      service:
        name: solr
        state: restarted

  tasks:
    - name: Install Java
      apt: name=openjdk-11-jre state=present

    - name: Download Solr
      get_url:
        url: "https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz" 
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz" # Name of the file
        checksum: "{{ solr_checksum }}"

    - name: Create Solr directory
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ solr_dir }}"
        remote_src: yes
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README.md"  # dacă un fișier/director există deja, sar peste dezarhivare

    - name: Run Solr installation script
      command: >
        {{ solr_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ solr_dir }}/solr-{{ solr_version }}.tgz 
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates= {{ solr_dir }}/bin/solr

    - name: Ensure Solr service is enabled and started
      service: name=solr state=started enabled=yes