Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"   # Ubuntu 22.04 LTS

  config.ssh.insert_key = false;

  config.vm.synced_folder ".", "/vagrant", disabled: true  # Dezactivează sincronizarea implicită

  # Setări VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"  # Increase memory to 1GB
    vb.linked_clone = true
  end

  # App server 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "orc-app1.test"
    app.vm.network :private_network, ip: "192.168.60.4"
  end

  # DB server 
  config.vm.define "db" do |app|
    app.vm.hostname = "orc-db.test"
    app.vm.network :private_network, ip: "192.168.60.5"
  end
end
