---
- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: yes
  tags: haproxy_install

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Ensure HAProxy is started and enabled
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true